spring:
  application:
    name: HelloClient

server:
  port: 7211


## cloud
eureka: 
  client:
    serviceUrl:
      defaultZone: http://192.168.100.102:1001/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    
    
    
endpoints:
  restart:
    enabled: true